# Generated by Django 4.0.3 on 2023-08-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintJob',
        ),
    ]
